// Every language Tesseract's fast trained-data set supports (from tessdata_fast,
// the same repo Tesseract.js pulls from by default) — 125 languages, generated
// from the actual repo listing rather than a hand-typed guess. Script-only files
// (Latin, Cyrillic, Arabic-the-script, etc.) are deliberately left out: a specific
// language's data includes a proper dictionary and is meaningfully more accurate
// than the generic multi-language data behind a bare script file.
//
// "equ" (math/equation recognition) is included since it's genuinely useful for
// scanning documents with formulas, even though it isn't a spoken language.
//
// Nothing here is bundled into the extension — each is fetched from Tesseract's
// CDN only if and when the user selects it, same as English already was.

export const LANGUAGES = [
  { code: "afr", name: "Afrikaans" },
  { code: "sqi", name: "Albanian" },
  { code: "amh", name: "Amharic" },
  { code: "grc", name: "Ancient Greek" },
  { code: "ara", name: "Arabic" },
  { code: "hye", name: "Armenian" },
  { code: "asm", name: "Assamese" },
  { code: "aze", name: "Azerbaijani" },
  { code: "aze_cyrl", name: "Azerbaijani (Cyrillic)" },
  { code: "eus", name: "Basque" },
  { code: "bel", name: "Belarusian" },
  { code: "ben", name: "Bengali" },
  { code: "bos", name: "Bosnian" },
  { code: "bre", name: "Breton" },
  { code: "bul", name: "Bulgarian" },
  { code: "mya", name: "Burmese" },
  { code: "cat", name: "Catalan" },
  { code: "ceb", name: "Cebuano" },
  { code: "chr", name: "Cherokee" },
  { code: "chi_sim", name: "Chinese (Simplified)" },
  { code: "chi_sim_vert", name: "Chinese (Simplified, vertical)" },
  { code: "chi_tra", name: "Chinese (Traditional)" },
  { code: "chi_tra_vert", name: "Chinese (Traditional, vertical)" },
  { code: "cos", name: "Corsican" },
  { code: "hrv", name: "Croatian" },
  { code: "ces", name: "Czech" },
  { code: "dan", name: "Danish" },
  { code: "div", name: "Dhivehi" },
  { code: "nld", name: "Dutch" },
  { code: "dzo", name: "Dzongkha" },
  { code: "eng", name: "English" },
  { code: "epo", name: "Esperanto" },
  { code: "est", name: "Estonian" },
  { code: "fao", name: "Faroese" },
  { code: "fil", name: "Filipino" },
  { code: "fin", name: "Finnish" },
  { code: "fra", name: "French" },
  { code: "glg", name: "Galician" },
  { code: "kat", name: "Georgian" },
  { code: "kat_old", name: "Georgian (old)" },
  { code: "deu", name: "German" },
  { code: "deu_latf", name: "German (Fraktur)" },
  { code: "frk", name: "German (old Fraktur print)" },
  { code: "ell", name: "Greek" },
  { code: "guj", name: "Gujarati" },
  { code: "hat", name: "Haitian Creole" },
  { code: "heb", name: "Hebrew" },
  { code: "hin", name: "Hindi" },
  { code: "hun", name: "Hungarian" },
  { code: "isl", name: "Icelandic" },
  { code: "ind", name: "Indonesian" },
  { code: "iku", name: "Inuktitut" },
  { code: "gle", name: "Irish" },
  { code: "ita", name: "Italian" },
  { code: "ita_old", name: "Italian (old)" },
  { code: "jpn", name: "Japanese" },
  { code: "jpn_vert", name: "Japanese (vertical)" },
  { code: "jav", name: "Javanese" },
  { code: "kan", name: "Kannada" },
  { code: "kaz", name: "Kazakh" },
  { code: "khm", name: "Khmer" },
  { code: "kor", name: "Korean" },
  { code: "kor_vert", name: "Korean (vertical)" },
  { code: "kmr", name: "Kurdish (Kurmanji)" },
  { code: "kir", name: "Kyrgyz" },
  { code: "lao", name: "Lao" },
  { code: "lat", name: "Latin" },
  { code: "lav", name: "Latvian" },
  { code: "lit", name: "Lithuanian" },
  { code: "ltz", name: "Luxembourgish" },
  { code: "mkd", name: "Macedonian" },
  { code: "msa", name: "Malay" },
  { code: "mal", name: "Malayalam" },
  { code: "mlt", name: "Maltese" },
  { code: "mri", name: "Maori" },
  { code: "mar", name: "Marathi" },
  { code: "equ", name: "Math / equations" },
  { code: "enm", name: "Middle English" },
  { code: "frm", name: "Middle French" },
  { code: "mon", name: "Mongolian" },
  { code: "nep", name: "Nepali" },
  { code: "nor", name: "Norwegian" },
  { code: "oci", name: "Occitan" },
  { code: "ori", name: "Odia" },
  { code: "pus", name: "Pashto" },
  { code: "fas", name: "Persian (Farsi)" },
  { code: "pol", name: "Polish" },
  { code: "por", name: "Portuguese" },
  { code: "pan", name: "Punjabi" },
  { code: "que", name: "Quechua" },
  { code: "ron", name: "Romanian" },
  { code: "rus", name: "Russian" },
  { code: "san", name: "Sanskrit" },
  { code: "gla", name: "Scottish Gaelic" },
  { code: "srp", name: "Serbian" },
  { code: "srp_latn", name: "Serbian (Latin)" },
  { code: "snd", name: "Sindhi" },
  { code: "sin", name: "Sinhala" },
  { code: "slk", name: "Slovak" },
  { code: "slv", name: "Slovenian" },
  { code: "spa", name: "Spanish" },
  { code: "spa_old", name: "Spanish (old)" },
  { code: "sun", name: "Sundanese" },
  { code: "swa", name: "Swahili" },
  { code: "swe", name: "Swedish" },
  { code: "syr", name: "Syriac" },
  { code: "tgk", name: "Tajik" },
  { code: "tam", name: "Tamil" },
  { code: "tat", name: "Tatar" },
  { code: "tel", name: "Telugu" },
  { code: "tha", name: "Thai" },
  { code: "bod", name: "Tibetan" },
  { code: "tir", name: "Tigrinya" },
  { code: "ton", name: "Tongan" },
  { code: "tur", name: "Turkish" },
  { code: "ukr", name: "Ukrainian" },
  { code: "urd", name: "Urdu" },
  { code: "uig", name: "Uyghur" },
  { code: "uzb", name: "Uzbek" },
  { code: "uzb_cyrl", name: "Uzbek (Cyrillic)" },
  { code: "vie", name: "Vietnamese" },
  { code: "cym", name: "Welsh" },
  { code: "fry", name: "Western Frisian" },
  { code: "yid", name: "Yiddish" },
  { code: "yor", name: "Yoruba" },];

export const DEFAULT_LANGUAGES = ["eng"];
